services:
  database:
    build:
      context: ./db
    image: the-rising-sigmas-database
    container_name: rs-database
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "SA", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 60s
    networks:
      - rs-network
    volumes:
      - db-data:/var/opt/mssql

  # .NET Backend API
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: rs-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=Server=database;Database=RisingSigma;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - rs-network

  # Ionic/Angular Frontend
  frontend:
    build:
      context: ./IONIC
      dockerfile: Dockerfile
    container_name: rs-frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:80
    depends_on:
      - backend
    networks:
      - rs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  adminer:
    image: adminer:latest
    container_name: rs-adminer
    ports:
      - "8090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DESIGN=pepa-linha
    depends_on:
      database:
        condition: service_healthy
    networks:
      - rs-network

volumes:
  db-data:
    name: rs-database-volume

networks:
  rs-network:
    driver: bridge
