services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.backend
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/Backend/RisingSigma.API
    command: dotnet run --urls=http://0.0.0.0:${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - rising-sigmas-network

  frontend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.frontend
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/IONIC
    command: npm install && ionic serve --host=0.0.0.0 --port=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - rising-sigmas-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - rising-sigmas-network

  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - rising-sigmas-network

networks:
  rising-sigmas-network:

volumes:
  mssqldata:
