FROM node:24.0.2

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y --no-install-recommends git curl unzip procps

RUN npm install -g @ionic/cli

RUN npm install -g @angular/cli