FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y --no-install-recommends git curl unzip procps

RUN dotnet tool install -g dotnet-ef

WORKDIR /workspace

ENV PATH="${PATH}:/root/.dotnet/tools"