version: "3.8"

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.workspace
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/IONIC/node_modules:delegated
      - dotnet_packages:/home/vscode/.nuget/packages:delegated
      - workspace_extensions:/home/vscode/.vscode-server/extensions:cached
    working_dir: /workspace
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ConnectionStrings__Database=Server=database;Database=RisingSigma;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - API_URL=http://localhost:5000
    command: sleep infinity
    ports:
      - "4200:4200"
      - "5000:5000"
      - "8100:8100"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      database:
        condition: service_healthy
    networks:
      - rising-sigmas-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=workspace"

  database:
    build:
      context: ./db
    container_name: rs-dev-database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "SA", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 60s
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - rising-sigmas-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        labels: "service=database"

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DEFAULT_DB=RisingSigma
      - ADMINER_DESIGN=pepa-linha
    ports:
      - "8090:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - rising-sigmas-network

networks:
  rising-sigmas-network:
    driver: bridge

volumes:
  mssqldata:
    name: rs-dev-database
    driver: local
  node_modules:
    name: rs-dev-node-modules
    driver: local
  dotnet_packages:
    name: rs-dev-dotnet-packages
    driver: local
  workspace_extensions:
    name: rs-dev-vscode-extensions
    driver: local
