name: Deploy Frontend to Azure Web App - rs-gymplan-web-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Code auschecken
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Node.js Setup (Ionic benötigt Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: npm install

      # 4. Build erstellen
      - name: Build the app
        run: npm run build

      # 5. Azure Login
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 6. Deployment
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "rs-gymplan-web-dev"
          slot-name: "Production"
          package: ./www
