name: Test Azure Login

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-login:
    runs-on: windows-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
