name: Build & Test API (no deploy)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Restore
        run: dotnet restore ./Backend/RisingSigma/RisingSigma.Api/RisingSigma.Api.csproj
      - name: Build
        run: dotnet build --configuration Release ./Backend/RisingSigma/RisingSigma.Api/RisingSigma.Api.csproj
      - name: Test
        run: dotnet test ./Backend/RisingSigma/RisingSigma.sln --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --collect "XPlat Code Coverage"
      - name: Upload test & coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: |
            **/TestResults/*.trx
            **/TestResults/*/coverage.cobertura.xml
      - name: Publish (artifact only)
        run: dotnet publish -c Release -o ./publish ./Backend/RisingSigma/RisingSigma.Api/RisingSigma.Api.csproj
      - name: Upload publish output
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ./publish
