name: Deploy Frontend to Azure Web App - rs-gymplan-web-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Code auschecken
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Node.js Setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          cd IONIC
          npm install

      # 4. Build erstellen
      - name: Build the app
        run: |
          cd IONIC
          npm run build

      # Debug: Verzeichnisinhalt anzeigen
      - name: List directory contents
        run: |
          cd IONIC
          dir
          cd www
          dir

      # 5. Deployment
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "rs-gymplan-web-dev"
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
          package: ./IONIC/www
