name: Test Azure Login

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-login:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C1E6820F768348448F1E391C95E48A79 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_96D42C4CB33743969BBE9FE1541A5E8F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4A7056F78DF4460581F216236AA88970 }}
