name: Test Azure Login

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-login:
    runs-on: windows-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        auth-type: IDENTITY
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
