name: Deploy API to Azure Web App - rs-gymplan-api-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      # 1. Code auschecken
      - name: Check out code
        uses: actions/checkout@v4

      # 2. .NET Core Setup
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      # 3. Restore
      - name: Restore dependencies
        run: dotnet restore ./Backend/RisingSigma/RisingSigma.API/RisingSigma.API.csproj

      # 4. Build
      - name: Build the project
        run: dotnet build --configuration Release ./Backend/RisingSigma/RisingSigma.API/RisingSigma.API.csproj

      # 5. Publish
      - name: Publish the app
        run: dotnet publish -c Release -o ./publish ./Backend/RisingSigma/RisingSigma.API/RisingSigma.API.csproj

      # 7. Deployment
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "rs-gymplan-api-dev"
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          slot-name: "Production"
          package: ./publish
