name: Test Azure Login

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-login:
    runs-on: self-hosted
    
    steps:
    - name: Debug Secrets
      run: |
        echo "${{ secrets.TEST }}"
        echo "Tenant ID: ${{ secrets.AZURE_TENANT_ID }}"
        echo "Subscription ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
    
    - name: Azure Login
      uses: azure/login@v2
      with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
